before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: vuWeEYlFIoRzJ7r5HTsgW4DSM+ZKhVoqbFipAvMMw5WiO4hAIFleZapD6Yd9ynI/xnqeGGuFV78/8ulh6qV2H0LESxM3gSkyFx/6sBGpD3xsoUPINdo4+l+InpftHbgTz9C9d6UF50NdW4ztCSvkh+umkj0BmSo4c2qiEDgoOWGi1om99+NxVQlddI08JZ+W/1CpAe+/ufISbHyWWhbq55yLFlwgiFNmMRPrdeJs4287D0KUeXlPEvsr3E5V504sgXKeOKYpmgkkWYx4ybYHWnz04NDbaVTGkaJOLUcKczGMdD2f+5+0/h7AI6ttOMnaNQe4QA7kjVPDUo/xdpMMuRWJxqQ//VEXEP0sI/Cj3WeB8GmlwuNtW1pdqc4oFJRMEVwcKT2xr8+4bhJu6MDhtkSzqCBgXWz+mS8gEZyIk6muaBCom0rMjI0HVT5k2E4qZ+BDWrLeFK6TP3TzWEimW1pi+GxGBgTYX8lAE0a/bitrJ5E8+ROiuuCrrF/BU0WBeG6alcYq8LdoDUys40ztjgnLhIdtIFj539lnDg5iWZX3+ISKcESppjaVyFMzGRCLgROlvarLoqLR7xEOR9ZN2HIbJH//7ISmkZeDw4sUul26vdjtBNxL3epkx/aXIM5lj+xvCGHfURvN3pTUaCW5gOcFPWhLYyRksAbwCTp1ZCY= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
